# Remove default compile flags provided with CMake for MSVC:
set (CMAKE_CXX_FLAGS "")
set (CMAKE_CXX_FLAGS_DEBUG "")
set (CMAKE_CXX_FLAGS_RELEASE "")

# Remove default linker flags provided with CMake for MSVC:
set (CMAKE_EXE_LINKER_FLAGS "")
set (CMAKE_MODULE_LINKER_FLAGS "")
set (CMAKE_SHARED_LINKER_FLAGS "")
set (CMAKE_STATIC_LINKER_FLAGS "")
set (CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS}")
set (CMAKE_MODULE_LINKER_FLAGS_DEBUG "${CMAKE_MODULE_LINKER_FLAGS}")
set (CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS}")
set (CMAKE_STATIC_LINKER_FLAGS_DEBUG "${CMAKE_STATIC_LINKER_FLAGS}")
set (CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS}")
set (CMAKE_MODULE_LINKER_FLAGS_RELEASE "${CMAKE_MODULE_LINKER_FLAGS}")
set (CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS}")
set (CMAKE_STATIC_LINKER_FLAGS_RELEASE "${CMAKE_STATIC_LINKER_FLAGS}")

# Set platform name:
set (CMAKE_PLATFORM ${CMAKE_CXX_COMPILER_ARCHITECTURE_ID})

# Set default OpenMP flags:
set (OpenMP_CXX_COMPILE_FLAGS "/openmp")